export const talentTextByLanguage = {
  en: {
    uploadKicker: 'Upload Your Talent',
    uploadHeading: 'Turn Waste Into Rewards Marketplace',
    uploadSubtitle:
      'Upload products you create from waste materials, set price and waste requirements, and help users redeem meaningful incentives.',
    uploadSuccessTitle: 'Talent uploaded successfully.',
    uploadSuccessDesc: 'Your upload has been saved. You can now view it in the Talent Gallery.',
    viewTalentGallery: 'View Talent Gallery',
    skillDetailsTitle: 'Your Skill Details',
    skillDetailsDesc: 'Add the skill you have, its price, and your contact details.',
    skillYouHave: 'Skill You Have',
    skillPlaceholder: 'Example: Handmade Craft, Recycled Art',
    category: 'Category',
    categoryOptions: {
      'Recycled Art': 'Recycled Art',
      'Handmade Craft': 'Handmade Craft',
      'Home Decor': 'Home Decor',
      'Utility Product': 'Utility Product',
      'Fashion Accessory': 'Fashion Accessory',
      Other: 'Other',
    },
    priceInr: 'Price (INR)',
    pricePlaceholder: 'Example: 120',
    wasteRequirement: 'Waste Requirement (KG)',
    wastePlaceholder: 'Example: 100',
    description: 'Description',
    descriptionPlaceholder: 'Describe what you create using waste materials',
    contactDetails: 'Contact Details (Phone/Email)',
    contactPlaceholder: 'Phone / WhatsApp / Email',
    uploadProductImage: 'Upload Product Image',
    noFileSelected: 'No file selected',
    saveTalent: 'Save Talent',
    savingTalent: 'Saving Talent...',
    wasteFinderTitle: 'Waste to Incentive Finder',
    wasteFinderDesc: 'Enter your collected waste and unlock products you can redeem right now.',
    collectedWaste: 'Collected Waste (KG)',
    finderPlaceholder: 'Example: 120',
    hint50: 'Recommended incentive price band: INR 20-INR 80',
    hint100: 'Recommended incentive price band: INR 50-INR 100',
    hint150: 'Recommended incentive price band: INR 100-INR 200',
    hint250: 'Recommended incentive price band: INR 200-INR 500',
    hintDefault: 'Enter collected waste in KG to see eligible rewards.',
    eligibleRewardsTitle: 'Eligible Rewards',
    eligibleSubtitleDefault: 'Products you can redeem based on entered waste (kg).',
    eligibleSubtitleBand: 'Products you can redeem now. Suggested price band for this waste is INR {min}-INR {max}.',
    allTalentProductsTitle: 'All Talent Products',
    allTalentProductsSubtitle: 'All uploaded products and demo incentives available on the platform.',
    noMatchingTalents: 'No matching talents yet.',
    noMatchingTalentsDesc: 'Try increasing waste KG or upload a new talent product.',
    contactNotProvided: 'Contact not provided',
    creativeProduct: 'Creative Product',
    requiresWaste: 'Requires {kg}kg waste',
    redeemBadge: 'You can redeem this',
    call: 'Call',
    message: 'Message',
    contactAria: 'Contact {title}',
  },
  hi: {
    uploadKicker: 'अपना टैलेंट अपलोड करें',
    uploadHeading: 'कचरे को रिवॉर्ड मार्केटप्लेस में बदलें',
    uploadSubtitle:
      'कचरे से बने अपने प्रोडक्ट अपलोड करें, कीमत और वेस्ट आवश्यकता सेट करें, और यूज़र्स को रिवॉर्ड रिडीम करने में मदद करें।',
    uploadSuccessTitle: 'टैलेंट सफलतापूर्वक अपलोड हुआ।',
    uploadSuccessDesc: 'आपका अपलोड सेव हो गया है। अब आप इसे टैलेंट गैलरी में देख सकते हैं।',
    viewTalentGallery: 'टैलेंट गैलरी देखें',
    skillDetailsTitle: 'आपकी स्किल डिटेल्स',
    skillDetailsDesc: 'अपनी स्किल, उसकी कीमत और संपर्क विवरण जोड़ें।',
    skillYouHave: 'आपके पास कौन सी स्किल है',
    skillPlaceholder: 'उदाहरण: हैंडमेड क्राफ्ट, रीसाइकल्ड आर्ट',
    category: 'श्रेणी',
    categoryOptions: {
      'Recycled Art': 'रीसाइकल्ड आर्ट',
      'Handmade Craft': 'हैंडमेड क्राफ्ट',
      'Home Decor': 'होम डेकोर',
      'Utility Product': 'यूटिलिटी प्रोडक्ट',
      'Fashion Accessory': 'फैशन एक्सेसरी',
      Other: 'अन्य',
    },
    priceInr: 'कीमत (INR)',
    pricePlaceholder: 'उदाहरण: 120',
    wasteRequirement: 'वेस्ट आवश्यकता (KG)',
    wastePlaceholder: 'उदाहरण: 100',
    description: 'विवरण',
    descriptionPlaceholder: 'बताएं कि आप कचरे से क्या बनाते हैं',
    contactDetails: 'संपर्क विवरण (फोन/ईमेल)',
    contactPlaceholder: 'फोन / व्हाट्सऐप / ईमेल',
    uploadProductImage: 'प्रोडक्ट इमेज अपलोड करें',
    noFileSelected: 'कोई फाइल चयनित नहीं',
    saveTalent: 'टैलेंट सेव करें',
    savingTalent: 'सेव किया जा रहा है...',
    wasteFinderTitle: 'वेस्ट टू इंसेंटिव फाइंडर',
    wasteFinderDesc: 'अपना एकत्रित वेस्ट डालें और देखें कौन से प्रोडक्ट अभी रिडीम कर सकते हैं।',
    collectedWaste: 'एकत्रित वेस्ट (KG)',
    finderPlaceholder: 'उदाहरण: 120',
    hint50: 'सुझाई गई प्राइस रेंज: INR 20-INR 80',
    hint100: 'सुझाई गई प्राइस रेंज: INR 50-INR 100',
    hint150: 'सुझाई गई प्राइस रेंज: INR 100-INR 200',
    hint250: 'सुझाई गई प्राइस रेंज: INR 200-INR 500',
    hintDefault: 'योग्य रिवॉर्ड देखने के लिए वेस्ट (KG) दर्ज करें।',
    eligibleRewardsTitle: 'योग्य रिवॉर्ड',
    eligibleSubtitleDefault: 'दर्ज वेस्ट (kg) के आधार पर रिडीम करने योग्य प्रोडक्ट।',
    eligibleSubtitleBand: 'आप अभी ये प्रोडक्ट रिडीम कर सकते हैं। सुझाई गई प्राइस रेंज: INR {min}-INR {max}।',
    allTalentProductsTitle: 'सभी टैलेंट प्रोडक्ट',
    allTalentProductsSubtitle: 'प्लेटफॉर्म पर अपलोड किए गए और डेमो इंसेंटिव प्रोडक्ट।',
    noMatchingTalents: 'कोई मेल खाता टैलेंट नहीं मिला।',
    noMatchingTalentsDesc: 'वेस्ट KG बढ़ाएं या नया टैलेंट प्रोडक्ट अपलोड करें।',
    contactNotProvided: 'संपर्क उपलब्ध नहीं',
    creativeProduct: 'क्रिएटिव प्रोडक्ट',
    requiresWaste: '{kg}kg वेस्ट आवश्यक',
    redeemBadge: 'आप इसे रिडीम कर सकते हैं',
    call: 'कॉल',
    message: 'मैसेज',
    contactAria: '{title} से संपर्क करें',
  },
  ur: {
    uploadKicker: 'اپنا ٹیلنٹ اپ لوڈ کریں',
    uploadHeading: 'فضلے کو ریوارڈ مارکیٹ پلیس میں بدلیں',
    uploadSubtitle:
      'فضلے سے بنے اپنے پروڈکٹس اپ لوڈ کریں، قیمت اور ویسٹ ضرورت سیٹ کریں، اور صارفین کو ریوارڈ ریڈیم کرنے میں مدد دیں۔',
    uploadSuccessTitle: 'ٹیلنٹ کامیابی سے اپ لوڈ ہو گیا۔',
    uploadSuccessDesc: 'آپ کا اپ لوڈ محفوظ ہو گیا ہے۔ اب آپ اسے ٹیلنٹ گیلری میں دیکھ سکتے ہیں۔',
    viewTalentGallery: 'ٹیلنٹ گیلری دیکھیں',
    skillDetailsTitle: 'آپ کی مہارت کی تفصیل',
    skillDetailsDesc: 'اپنی مہارت، قیمت اور رابطہ تفصیل شامل کریں۔',
    skillYouHave: 'آپ کے پاس کون سی مہارت ہے',
    skillPlaceholder: 'مثال: Handmade Craft, Recycled Art',
    category: 'زمرہ',
    categoryOptions: {
      'Recycled Art': 'ری سائیکلڈ آرٹ',
      'Handmade Craft': 'ہینڈ میڈ کرافٹ',
      'Home Decor': 'ہوم ڈیکور',
      'Utility Product': 'یوٹیلٹی پروڈکٹ',
      'Fashion Accessory': 'فیشن ایکسسری',
      Other: 'دیگر',
    },
    priceInr: 'قیمت (INR)',
    pricePlaceholder: 'مثال: 120',
    wasteRequirement: 'ویسٹ ضرورت (KG)',
    wastePlaceholder: 'مثال: 100',
    description: 'تفصیل',
    descriptionPlaceholder: 'بتائیں کہ آپ فضلے سے کیا بناتے ہیں',
    contactDetails: 'رابطہ تفصیل (فون/ای میل)',
    contactPlaceholder: 'فون / واٹس ایپ / ای میل',
    uploadProductImage: 'پروڈکٹ تصویر اپ لوڈ کریں',
    noFileSelected: 'کوئی فائل منتخب نہیں ہوئی',
    saveTalent: 'ٹیلنٹ محفوظ کریں',
    savingTalent: 'محفوظ کیا جا رہا ہے...',
    wasteFinderTitle: 'ویسٹ ٹو انسینٹو فائنڈر',
    wasteFinderDesc: 'اپنا جمع شدہ ویسٹ درج کریں اور دیکھیں کون سے پروڈکٹس ابھی ریڈیم کر سکتے ہیں۔',
    collectedWaste: 'جمع شدہ ویسٹ (KG)',
    finderPlaceholder: 'مثال: 120',
    hint50: 'تجویز کردہ قیمت رینج: INR 20-INR 80',
    hint100: 'تجویز کردہ قیمت رینج: INR 50-INR 100',
    hint150: 'تجویز کردہ قیمت رینج: INR 100-INR 200',
    hint250: 'تجویز کردہ قیمت رینج: INR 200-INR 500',
    hintDefault: 'اہل ریوارڈ دیکھنے کے لیے ویسٹ (KG) درج کریں۔',
    eligibleRewardsTitle: 'اہل ریوارڈز',
    eligibleSubtitleDefault: 'درج ویسٹ (kg) کے مطابق ریڈیم ہونے والے پروڈکٹس۔',
    eligibleSubtitleBand: 'آپ ابھی یہ پروڈکٹس ریڈیم کر سکتے ہیں۔ تجویز کردہ قیمت رینج: INR {min}-INR {max}۔',
    allTalentProductsTitle: 'تمام ٹیلنٹ پروڈکٹس',
    allTalentProductsSubtitle: 'پلیٹ فارم پر اپ لوڈ شدہ اور ڈیمو انسینٹو پروڈکٹس۔',
    noMatchingTalents: 'کوئی مماثل ٹیلنٹ نہیں ملا۔',
    noMatchingTalentsDesc: 'ویسٹ KG بڑھائیں یا نیا ٹیلنٹ پروڈکٹ اپ لوڈ کریں۔',
    contactNotProvided: 'رابطہ دستیاب نہیں',
    creativeProduct: 'کریئیٹو پروڈکٹ',
    requiresWaste: '{kg}kg ویسٹ ضروری',
    redeemBadge: 'آپ اسے ریڈیم کر سکتے ہیں',
    call: 'کال',
    message: 'پیغام',
    contactAria: '{title} سے رابطہ کریں',
  },
  bn: {
    uploadKicker: 'আপনার ট্যালেন্ট আপলোড করুন',
    uploadHeading: 'বর্জ্যকে রিওয়ার্ড মার্কেটপ্লেসে রূপান্তর করুন',
    uploadSubtitle:
      'বর্জ্য দিয়ে তৈরি আপনার পণ্য আপলোড করুন, মূল্য ও বর্জ্যের প্রয়োজন সেট করুন, এবং ব্যবহারকারীদের রিওয়ার্ড রিডিম করতে সাহায্য করুন।',
    uploadSuccessTitle: 'ট্যালেন্ট সফলভাবে আপলোড হয়েছে।',
    uploadSuccessDesc: 'আপনার আপলোড সংরক্ষিত হয়েছে। এখন আপনি এটি ট্যালেন্ট গ্যালারিতে দেখতে পারবেন।',
    viewTalentGallery: 'ট্যালেন্ট গ্যালারি দেখুন',
    skillDetailsTitle: 'আপনার স্কিল ডিটেইলস',
    skillDetailsDesc: 'আপনার স্কিল, দাম এবং যোগাযোগের তথ্য যোগ করুন।',
    skillYouHave: 'আপনার কী স্কিল আছে',
    skillPlaceholder: 'উদাহরণ: Handmade Craft, Recycled Art',
    category: 'ক্যাটাগরি',
    categoryOptions: {
      'Recycled Art': 'রিসাইকেলড আর্ট',
      'Handmade Craft': 'হ্যান্ডমেড ক্রাফট',
      'Home Decor': 'হোম ডেকর',
      'Utility Product': 'ইউটিলিটি প্রোডাক্ট',
      'Fashion Accessory': 'ফ্যাশন অ্যাক্সেসরি',
      Other: 'অন্যান্য',
    },
    priceInr: 'দাম (INR)',
    pricePlaceholder: 'উদাহরণ: 120',
    wasteRequirement: 'বর্জ্য প্রয়োজন (KG)',
    wastePlaceholder: 'উদাহরণ: 100',
    description: 'বর্ণনা',
    descriptionPlaceholder: 'বর্জ্য থেকে আপনি কী তৈরি করেন তা লিখুন',
    contactDetails: 'যোগাযোগের তথ্য (ফোন/ইমেইল)',
    contactPlaceholder: 'ফোন / হোয়াটসঅ্যাপ / ইমেইল',
    uploadProductImage: 'পণ্যের ছবি আপলোড করুন',
    noFileSelected: 'কোনো ফাইল নির্বাচন করা হয়নি',
    saveTalent: 'ট্যালেন্ট সংরক্ষণ করুন',
    savingTalent: 'সংরক্ষণ করা হচ্ছে...',
    wasteFinderTitle: 'ওয়েস্ট টু ইনসেন্টিভ ফাইন্ডার',
    wasteFinderDesc: 'আপনার সংগৃহীত বর্জ্য লিখুন এবং দেখুন কোন পণ্য এখন রিডিম করতে পারবেন।',
    collectedWaste: 'সংগৃহীত বর্জ্য (KG)',
    finderPlaceholder: 'উদাহরণ: 120',
    hint50: 'প্রস্তাবিত মূল্য সীমা: INR 20-INR 80',
    hint100: 'প্রস্তাবিত মূল্য সীমা: INR 50-INR 100',
    hint150: 'প্রস্তাবিত মূল্য সীমা: INR 100-INR 200',
    hint250: 'প্রস্তাবিত মূল্য সীমা: INR 200-INR 500',
    hintDefault: 'যোগ্য রিওয়ার্ড দেখতে বর্জ্য (KG) লিখুন।',
    eligibleRewardsTitle: 'যোগ্য রিওয়ার্ড',
    eligibleSubtitleDefault: 'দেওয়া বর্জ্য (kg) অনুযায়ী রিডিমযোগ্য পণ্য।',
    eligibleSubtitleBand: 'আপনি এখন এই পণ্যগুলো রিডিম করতে পারেন। প্রস্তাবিত মূল্য সীমা: INR {min}-INR {max}।',
    allTalentProductsTitle: 'সব ট্যালেন্ট পণ্য',
    allTalentProductsSubtitle: 'প্ল্যাটফর্মে আপলোড করা ও ডেমো ইনসেন্টিভ পণ্যসমূহ।',
    noMatchingTalents: 'মিলছে এমন ট্যালেন্ট পাওয়া যায়নি।',
    noMatchingTalentsDesc: 'বর্জ্য KG বাড়ান বা নতুন ট্যালেন্ট পণ্য আপলোড করুন।',
    contactNotProvided: 'যোগাযোগ দেওয়া নেই',
    creativeProduct: 'ক্রিয়েটিভ পণ্য',
    requiresWaste: '{kg}kg বর্জ্য প্রয়োজন',
    redeemBadge: 'আপনি এটি রিডিম করতে পারবেন',
    call: 'কল',
    message: 'মেসেজ',
    contactAria: '{title} এর সাথে যোগাযোগ করুন',
  },
  mr: {
    uploadKicker: 'तुमचा टॅलेंट अपलोड करा',
    uploadHeading: 'कचऱ्याला रिवॉर्ड मार्केटप्लेसमध्ये बदला',
    uploadSubtitle:
      'कचऱ्यापासून बनवलेली उत्पादने अपलोड करा, किंमत आणि वेस्ट आवश्यकता सेट करा, आणि वापरकर्त्यांना रिवॉर्ड रिडीम करण्यात मदत करा.',
    uploadSuccessTitle: 'टॅलेंट यशस्वीरित्या अपलोड झाले.',
    uploadSuccessDesc: 'तुमचे अपलोड सेव झाले आहे. आता तुम्ही ते टॅलेंट गॅलरीत पाहू शकता.',
    viewTalentGallery: 'टॅलेंट गॅलरी पहा',
    skillDetailsTitle: 'तुमच्या कौशल्याची माहिती',
    skillDetailsDesc: 'तुमचे कौशल्य, किंमत आणि संपर्क तपशील जोडा.',
    skillYouHave: 'तुमच्याकडे कोणते कौशल्य आहे',
    skillPlaceholder: 'उदाहरण: Handmade Craft, Recycled Art',
    category: 'श्रेणी',
    categoryOptions: {
      'Recycled Art': 'रीसायकल्ड आर्ट',
      'Handmade Craft': 'हँडमेड क्राफ्ट',
      'Home Decor': 'होम डेकोर',
      'Utility Product': 'युटिलिटी प्रॉडक्ट',
      'Fashion Accessory': 'फॅशन अॅक्सेसरी',
      Other: 'इतर',
    },
    priceInr: 'किंमत (INR)',
    pricePlaceholder: 'उदाहरण: 120',
    wasteRequirement: 'वेस्ट आवश्यकता (KG)',
    wastePlaceholder: 'उदाहरण: 100',
    description: 'वर्णन',
    descriptionPlaceholder: 'तुम्ही कचऱ्यापासून काय बनवता ते सांगा',
    contactDetails: 'संपर्क तपशील (फोन/ईमेल)',
    contactPlaceholder: 'फोन / व्हॉट्सअॅप / ईमेल',
    uploadProductImage: 'प्रॉडक्ट फोटो अपलोड करा',
    noFileSelected: 'कोणतीही फाइल निवडलेली नाही',
    saveTalent: 'टॅलेंट सेव करा',
    savingTalent: 'सेव होत आहे...',
    wasteFinderTitle: 'वेस्ट टू इन्सेंटिव्ह फाइंडर',
    wasteFinderDesc: 'तुमचा जमा केलेला वेस्ट भरा आणि आत्ताच कोणती उत्पादने रिडीम करता येतील ते पहा.',
    collectedWaste: 'जमा वेस्ट (KG)',
    finderPlaceholder: 'उदाहरण: 120',
    hint50: 'सुचवलेली किंमत रेंज: INR 20-INR 80',
    hint100: 'सुचवलेली किंमत रेंज: INR 50-INR 100',
    hint150: 'सुचवलेली किंमत रेंज: INR 100-INR 200',
    hint250: 'सुचवलेली किंमत रेंज: INR 200-INR 500',
    hintDefault: 'पात्र रिवॉर्ड पाहण्यासाठी वेस्ट (KG) भरा.',
    eligibleRewardsTitle: 'पात्र रिवॉर्ड्स',
    eligibleSubtitleDefault: 'भरलेल्या वेस्ट (kg) नुसार रिडीम होणारी उत्पादने.',
    eligibleSubtitleBand: 'तुम्ही आता ही उत्पादने रिडीम करू शकता. सुचवलेली किंमत रेंज: INR {min}-INR {max}.',
    allTalentProductsTitle: 'सर्व टॅलेंट उत्पादने',
    allTalentProductsSubtitle: 'प्लॅटफॉर्मवरील सर्व अपलोडेड आणि डेमो इन्सेंटिव्ह उत्पादने.',
    noMatchingTalents: 'जुळणारे टॅलेंट आढळले नाही.',
    noMatchingTalentsDesc: 'वेस्ट KG वाढवा किंवा नवीन टॅलेंट प्रॉडक्ट अपलोड करा.',
    contactNotProvided: 'संपर्क उपलब्ध नाही',
    creativeProduct: 'क्रिएटिव्ह प्रॉडक्ट',
    requiresWaste: '{kg}kg वेस्ट आवश्यक',
    redeemBadge: 'तुम्ही हे रिडीम करू शकता',
    call: 'कॉल',
    message: 'मेसेज',
    contactAria: '{title} शी संपर्क करा',
  },
};

export const getTalentText = (language) => {
  const selected = talentTextByLanguage[language] || {};
  return { ...talentTextByLanguage.en, ...selected };
};
